### ISSUE TITLE
Выравнивание текста в каталоге коллекции

### ISSUE THREAD

**Issue by vitkarpov** [vitkarpov/parket-st#19]
![](http://puu.sh/lWkOH/16749c7f8d.png)

Должно присутствовать выравнивание текста.

**Comment by vitkarpov** [comment]
Высота блоков должна быть строго определена. При таком подходе, придется зафиксировать высоту для названия, а цену прибить к низу.

Если название будет в одну строку или фоточка окажется меньшего размера, то будут дырки внутри блока. Это норм?

Рассчитываем на то, что фоточки будут правильно подобраны и названия более или менее большими?

**Comment by goodcode1** [comment]
@vitkarpov, решили вопрос. Делать ничего не нужно, всё оставляем как есть.

**Comment by vitkarpov** [comment]
Спасибо
