### ISSUE TITLE
Добавить «еще» к списку рекомендаций

### ISSUE THREAD

**Issue by vitkarpov** [vitkarpov/parket-st#2]
![](https://yadi.sk/i/kQaJtBZmmFTri_XL.jpg)

Забыли вкрутить обновление списка

**Comment by vitkarpov** [comment]
Аналогично добавлению товаров в попап коризны — норм будет если здесь мне на запрос будет возвращаться весь html блока?

**Comment by goodcode1** [comment]
Да, вполне норм.

**Comment by vitkarpov** [comment]
В параметрах блока `suggest` нужно указать урл — туда будем делать запрос за html

![](https://yadi.sk/i/wkQvjV4QmLbbt_XL.jpg)
- `start` изначально активный пункт меню (вряд ли придется менять, но мало ли)
- `url` куда ходить за новым контентом

Отправлять нужно **только то, что находится внутри `suggest__content`**

![](https://yadi.sk/i/DzK2hZ1YmLbT2_XL.jpg)

На завершение запроса весь контент из `suggest__content` удаляется и заменяется вновь прибывшим html.
